### ISSUE TITLE
Download dataset from zenodo

### ISSUE THREAD

**Issue by navidcy** [josuemtzmo/EKE_SST_trends#15]
We should include how one can download the dataset from zenodo. We should have instructions here:
https://github.com/josuemtzmo/EKE_SST_trends/blob/master/datasets/README.md

I tried to do it and it wasn't at all obvious. @josuemtzmo, how would you download the dataset to gadi or to any HPC you are connected via ssh?

**Comment by josuemtzmo** [comment]
For record, I've added the following lines in the main ReadMe.md:

The pre-processed datasets can be downloaded from  <a href="https://doi.org/10.5281/zenodo.3993824"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.3993824.svg" alt="zenodo doi"></a>. To facilitate the download of all `*.nc` files, install <a href="https://doi.org/10.5281/zenodo.3993824">Zenodo_get</a>:
```
pip install zenodo-get
```
all the datasets can be downloaded by running:
```
zenodo_get 10.5281/zenodo.3993824
```
> **WARNING**: It is required ~16 GB of disk space to download the full pre-processed dataset.
