### ISSUE TITLE
Inconsistency before cell #1 in SST_gradient_maps.ipynb

### ISSUE THREAD

**Issue by navidcy** [josuemtzmo/EKE_SST_trends#9]
The left-hand and right-hand sides of the second mathematical expression are not consistent to one another.

**Comment by josuemtzmo** [comment]
The equation was replaced to:

![Screen Shot 2021-01-11 at 10 21 07 am](https://user-images.githubusercontent.com/9144063/104138205-bb0a3280-53f6-11eb-9803-9a385e6cdd4b.png)
